import type { Profile } from '@hiddengeniuslabs/genius-mining';
import { CONFIDENCE_NOTE, describeThinSpot, safeText } from '@/lib/gm/render';

export type AdvisorPrintoutProps = {
  profile: Profile;
  d3Sentence: string;
  campusName: string;
};

const CONFIDENCE_STYLES: Record<string, string> = {
  HIGH: 'border-green-600 text-green-800 bg-green-50',
  MEDIUM: 'border-gold-600 text-brand-900 bg-gold-400/20',
  LOW: 'border-red-500 text-red-800 bg-red-50',
};

/**
 * The advisor printout: same profile object, different job.
 *
 * The student takes this to a parent or an academic advisor, so it has to show
 * its own workings — the evidence, the confidence, the answers that were too thin
 * to use, the instrument version and the run date. An advisor who sees MEDIUM
 * confidence and three sparse answers reads it correctly as a conversation
 * starter. One who sees a confident word in a nice font may treat it as a result,
 * which is why "a starting place, not a verdict" sits where the advisor reads it
 * and not only where the student does.
 */
export default function AdvisorPrintout({
  profile,
  d3Sentence,
  campusName,
}: AdvisorPrintoutProps) {
  const thinSpots = profile.thin_spots ?? [];
  const evidence = safeText(profile.evidence, thinSpots);
  const bodySignal = safeText(profile.body_signal_read, thinSpots);
  const tallyUnresolved = profile.d1_resolution?.resolution === 'UNRESOLVED';
  const isMock = profile.model === 'mock-engine';

  return (
    <article className="mx-auto max-w-[46rem] bg-white p-8 text-brand-900 print:p-0">
      <header className="border-b-2 border-brand-900 pb-4">
        <div className="flex items-baseline justify-between gap-4">
          <div>
            <p className="text-xs font-bold uppercase tracking-[0.18em] text-brand-500">
              Genius Mining · CampusQuest
            </p>
            <h1 className="mt-1.5 text-2xl font-extrabold">Genius Profile</h1>
          </div>
          <p className="text-right text-xs text-brand-600 tabular-nums">
            {profile.participant_code}
            <br />
            {new Date(profile.run_at).toLocaleDateString('en-US', {
              year: 'numeric',
              month: 'long',
              day: 'numeric',
            })}
          </p>
        </div>

        <p className="mt-4 border-l-4 border-gold-500 bg-gold-400/15 px-4 py-2.5 text-sm font-bold">
          This is a starting place, not a verdict. It describes a pattern in what one student wrote
          on one afternoon. It is not an assessment, a diagnosis, or advice about what to study.
        </p>
      </header>

      {isMock ? (
        <p className="mt-5 border-2 border-red-500 bg-red-50 px-4 py-2.5 text-sm font-bold text-red-800">
          Generated by a development stand-in, not by the analysis engine. Not a reading. Do not
          share with a student or an advisor.
        </p>
      ) : null}

      <section className="mt-6">
        <div className="flex flex-wrap items-center gap-4">
          <div>
            <p className="text-xs font-bold uppercase tracking-wide text-brand-500">Working word</p>
            <p className="mt-1 text-4xl font-extrabold tracking-tight">
              {profile.primary_working_word}
            </p>
          </div>
          <p
            className={`ml-auto rounded-md border-2 px-3 py-1.5 text-sm font-bold ${
              CONFIDENCE_STYLES[profile.confidence] ?? ''
            }`}
          >
            {profile.confidence} confidence
          </p>
        </div>
        <p className="mt-2 text-sm text-brand-600">{CONFIDENCE_NOTE[profile.confidence]}</p>
      </section>

      {d3Sentence ? (
        <section className="mt-6">
          <h2 className="text-xs font-bold uppercase tracking-wide text-brand-500">
            The student&rsquo;s own sentence (D3)
          </h2>
          <p className="mt-1.5 border-l-2 border-brand-300 pl-4 text-lg leading-relaxed">
            &ldquo;{d3Sentence}&rdquo;
          </p>
        </section>
      ) : null}

      {evidence.text ? (
        <section className="mt-6">
          <h2 className="text-xs font-bold uppercase tracking-wide text-brand-500">Evidence</h2>
          <p className="mt-1.5 leading-relaxed">{evidence.text}</p>
        </section>
      ) : null}

      <div className="mt-6 grid gap-6 sm:grid-cols-2">
        {bodySignal.text ? (
          <section>
            <h2 className="text-xs font-bold uppercase tracking-wide text-brand-500">
              Body signal (C2)
            </h2>
            <p className="mt-1.5 text-sm leading-relaxed">{bodySignal.text}</p>
          </section>
        ) : null}

        <section>
          <h2 className="text-xs font-bold uppercase tracking-wide text-brand-500">
            Secondary pattern
          </h2>
          {profile.secondary_pattern?.word ? (
            <p className="mt-1.5 text-sm leading-relaxed">
              <span className="font-bold">{profile.secondary_pattern.word}</span> —{' '}
              {profile.secondary_pattern.note}
            </p>
          ) : (
            <p className="mt-1.5 text-sm text-brand-600">{profile.secondary_pattern?.note}</p>
          )}
        </section>
      </div>

      <section className="mt-6 border border-brand-200 bg-brand-50 p-5">
        <h2 className="text-xs font-bold uppercase tracking-wide text-brand-500">
          How the student&rsquo;s own tally compares
        </h2>
        <p className="mt-1.5 text-sm leading-relaxed">
          {profile.disagreement_with_self_tally.reason}
        </p>

        {tallyUnresolved ? (
          <p className="mt-3 border-t border-brand-200 pt-3 text-sm">
            <span className="font-bold">The verb count did not resolve.</span> It tied between{' '}
            {profile.d1_resolution?.candidates?.join(' and ')}, and the form&rsquo;s tiebreak did not
            separate them either.{' '}
            {profile.d1_resolution?.student_tiebreak_choice
              ? `The student chose ${profile.d1_resolution.student_tiebreak_choice}.`
              : 'No choice was recorded.'}{' '}
            The word above rests on what they wrote, not on the arithmetic.
          </p>
        ) : null}
      </section>

      <section className="mt-6">
        <h2 className="text-xs font-bold uppercase tracking-wide text-brand-500">
          Answers too thin to use
        </h2>
        {thinSpots.length > 0 ? (
          <>
            <ul className="mt-2 space-y-1 text-sm">
              {thinSpots.map((spot) => (
                <li key={spot} className="flex gap-2">
                  <span className="font-mono font-bold text-brand-700">{spot}</span>
                  <span className="text-brand-700">{describeThinSpot(spot)}</span>
                </li>
              ))}
            </ul>
            <p className="mt-2.5 text-sm text-brand-600">
              Nothing on this page is drawn from these. They are listed because a reading built on
              fewer answers deserves less weight, and because they are the obvious things to ask
              about in person.
            </p>
          </>
        ) : (
          <p className="mt-1.5 text-sm text-brand-600">
            None. Every answer was substantial enough to use.
          </p>
        )}
      </section>

      <section className="mt-6 border-2 border-brand-900 p-5">
        <h2 className="text-sm font-extrabold">For the mentor</h2>
        <p className="mt-2 leading-relaxed">{profile.for_the_mentor}</p>
        <p className="mt-3 text-sm text-brand-600">
          This question exists so a person can break the finding if it deserves breaking. If the
          student&rsquo;s answer to it contradicts the word above, the word is wrong and the
          conversation is the point.
        </p>
      </section>

      {profile.student_edits?.length ? (
        <section className="mt-6">
          <h2 className="text-xs font-bold uppercase tracking-wide text-brand-500">
            Lines the student rewrote
          </h2>
          <ul className="mt-2 space-y-2.5 text-sm">
            {profile.student_edits.map((edit) => (
              <li key={`${edit.field}-${edit.edited_at}`}>
                <span className="font-mono font-bold text-brand-700">{edit.field}</span>
                <span className="mt-0.5 block text-brand-600 line-through">{edit.original}</span>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <footer className="mt-8 border-t border-brand-300 pt-4 text-xs text-brand-600">
        <dl className="grid grid-cols-2 gap-x-6 gap-y-1 sm:grid-cols-4">
          <div>
            <dt className="font-bold">Instrument</dt>
            <dd className="tabular-nums">v{profile.instrument_version}</dd>
          </div>
          <div>
            <dt className="font-bold">Engine</dt>
            <dd className="tabular-nums">{profile.engine_version}</dd>
          </div>
          <div>
            <dt className="font-bold">Model</dt>
            <dd className="font-mono">{profile.model}</dd>
          </div>
          <div>
            <dt className="font-bold">Campus</dt>
            <dd>{campusName}</dd>
          </div>
        </dl>
        <p className="mt-3">
          Genius Mining is owned by Hidden Genius Labs LLC and licensed to CampusQuest. Analysis is
          performed by a third-party model on responses with the student&rsquo;s name removed.
        </p>
      </footer>
    </article>
  );
}
